// JavaScript Document
var navigation = "<div id='navList1'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/company_information/Pages/default.aspx' class='header'>Company Information</a></li>"
navigation += "<li><a href='http://www.thekrogerco.com/'>About The Kroger Co.</a></li>"
navigation += "<li><a href='http://www.thekrogerco.com/corpnews/corpnewsinfo.htm'>Company News</a></li>"
navigation += "<li><a href='http://www.thekrogerco.com/finance/financialinfo.htm'>Investor Relations</a></li>"
navigation += "<li><a href='http://www.thekrogerco.com/finance/financialinfo_reportsandstatements.htm'>SEC Filings</a></li>"
navigation += "<li><a href='http://www.kroger.com/company_information/community/Pages/default.aspx'>Community</a></li>"
navigation += "<li><a href='http://www.krogerrealestate.com/'>Kroger Real Estate</a></li>"
navigation += "<li><a href='http://www.kroger.com/company_information/careers/Pages/default.aspx'>Careers/Jobs</a></li>"
navigation += "<li><a href='https://ess.kroger.com/'>Express HR/Associates</a></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div id='navList2'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/default.aspx' class='header'>Services</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/recall_information.aspx'>Recall Information</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/finance/Pages/default.aspx'>1-2-3 REWARDS&reg; Visa&reg;</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/finance/debit/Pages/default.aspx'>Visa&reg; Prepaid Debit Card</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/specialty_grocery.aspx'>Specialty Grocery</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/school_programs.aspx'>School Programs</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/phone_services.aspx'>Phone Services</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/partners.aspx'>Partners</a></li>"
navigation += "<li><a href='http://www.communitygifts.com/kroger'>Request a Donation</a></li>"
navigation += "<li><a href='http://www.kroger.com/mykroger/Pages/community_rewards.aspx'>Community Rewards</a></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div id='navList3'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/help/Pages/default.aspx' class='header'>Help</a></li>"
navigation += "<li><a href='http://www.kroger.com/help/Pages/contact_us.aspx'>Contact Us</a></li>"
navigation += "<li><a href='https://customer.kroger.com/comments/comments.aspx'>Customer Comments</a></li>"
navigation += "<li><a href='http://recipes.kroger.com/faqs/browse.aspx'>FAQs</a></li>"
navigation += "<li><a href='http://www.kroger.com/help/Pages/site_map.aspx'>Site Map</a></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div id='navList4'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/stores/Pages/default.aspx' class='header'>Stores</a></li>"
navigation += "<li><a href='http://services.kroger.com/StoreLocator/StoreLocatorAdvanced.aspx'>Store Locator</a></li>"
navigation += "<li><a href='http://services.kroger.com/StoreLocator/StoreLocatorWeeklyAdSearch.aspx'>Weekly Ads</a></li>"
navigation += "</ul>"
navigation += "</div>"
document.write(navigation);