// JavaScript Document
//11/13/07
var navigation = "<li class='pipe' id='mainNav_pipe1'></li>"
navigation += "<li id='mainNav_item1'><a href='http://www.kroger.com' class='main'><img src='http://www.kroger.com/SiteCollectionImages/common/navigation/kroger/mainNav_Home.gif' id='ctl00_Img1' alt='image' title='Home' /></a></li>"
navigation += "<li class='pipe' id='mainNav_pipe2'></li>"
navigation += "<li id='mainNav_item2'><a href='http://www.kroger.com/great_meals' class='main'><img src='http://www.kroger.com/SiteCollectionImages/common/navigation/kroger/mainNav_Great_Meals.gif' id='ctl00_Img2' alt='image' title='Great Meals' /></a>"
navigation += "<ul id='mainNav_item2-menu' class='hide'>"
navigation += "<li><a  href='http://www.kroger.com/great_meals/recipes/Pages/default.aspx'>Recipes</a></li>"
navigation += "<li><a  href='http://www.kroger.com/great_meals/party_planning/Pages/default.aspx'>Party Planning</a></li>" 
navigation += "<li><a  href='http://www.kroger.com/great_meals/safe_food_preparation/Pages/default.aspx'>Safe Food Preparation</a></li>"
navigation += "<li><a  href='http://www.kroger.com/great_meals/party_trays/Pages/default.aspx'>Party Trays</a></li>"
navigation += "<li><a  href='http://www.krogerbeerevents.com'>Beer</a></li>"
navigation += "<li><a  href='http://www.krogerwineevents.com'>Wine</a></li>"
navigation += "<li><a  href='http://krogerspiritevents.com/'>Spirits</a></li>"  
navigation += "</ul>"
navigation += "</li>"
navigation += "<li class='pipe' id='mainNav_pipe3'></li>"
navigation += "<li id='mainNav_item3'><a href='http://www.kroger.com/healthy_living' class='main'><img src='http://www.kroger.com/SiteCollectionImages/common/navigation/kroger/mainNav_Healthy_Living.gif' id='ctl00_Img3' alt='image' title='Healthy Living' /></a>"
navigation += "<ul id='mainNav_item3-menu' class='hide'>"
navigation += "<li><a href='http://kroger.staywellsolutionsonline.com/'>Health Guide</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/the_little_clinic.aspx'>The Little Clinic</a></li>"
navigation += "<li><a href='http://www.kroger.com/healthy_living/family/Pages/default.aspx'>Home & Family</a></li>"
navigation += "<li><a href='http://www.kroger.com/healthy_living/fitness_nutrition/Pages/default.aspx'>Fitness & Nutrition</a></li>"
navigation += "<li><a href='http://www.kroger.com/healthy_living/green_living/Pages/default.aspx'>Green Living</a></li>"
navigation += "<li><a href='http://www.kroger.com/healthy_living/gluten_free/Pages/default.aspx'>Gluten Free</a></li>"
navigation += "</ul>"
navigation += "<iframe id='mainNav_item3-shim' class='navShim' scrolling='no' frameborder='0' src='javascript:false;'></iframe>"
navigation += "</li>"
navigation += "<li class='pipe' id='mainNav_pipe4'></li>"
navigation += "<li id='mainNav_item4'><a href='http://www.kroger.com/fresh_foods' class='main'><img src='http://www.kroger.com/SiteCollectionImages/common/navigation/kroger/mainNav_Fresh_Foods.gif' id='ctl00_Img4' alt='image' title='Fresh Foods' /></a>"
navigation += "<ul id='mainNav_item4-menu' class='hide'>"
navigation += "<li><a href='http://www.kroger.com/fresh_foods/deli_bakery/Pages/default.aspx'>Deli & Bakery</a></li>"
navigation += "<li><a href='http://www.kroger.com/fresh_foods/fruits_veggies/Pages/default.aspx'>Fruits & Veggies</a></li>"
navigation += "<li class='noBorder'><a href='http://www.kroger.com/fresh_foods/meat_seafood/Pages/default.aspx'>Meat & Seafood</a></li>"
navigation += "</ul>"
navigation += "<iframe id='mainNav_item4-shim' class='navShim' scrolling='no' frameborder='0' src='javascript:false;'></iframe>"
navigation += "</li>"
navigation += "<li class='pipe' id='mainNav_pipe5'></li>"
navigation += "<li id='mainNav_item5'><a href='http://www.kroger.com/gift_center' class='main'><img src='http://www.kroger.com/SiteCollectionImages/common/navigation/kroger/mainNav_Gift_Center.gif' id='ctl00_Img5' alt='image' title='GiftCenter' /></a>"
navigation += "<ul id='mainNav_item5-menu' class='hide'>"
navigation += "<li><a href='http://www.kroger.com/gift_center/gc/Pages/default.aspx'>Buy Gift Cards</a></li>"
navigation += "<li><a href='http://ftdfloristsonline.com/kroger'>Flowers</a></li>"
navigation += "<li><a href='http://www.kroger.com/gift_center/Pages/gourmet_gifts.aspx'>Gourmet Gifts</a></li>"
navigation += "<li><a href='http://www.kroger.com/gift_center/Pages/jewelry.aspx'>Fred Meyer Jewelers</a></li>"
navigation += "</ul>"
navigation += "<iframe id='mainNav_item5-shim' class='navShim' scrolling='no' frameborder='0' src='javascript:false;'></iframe>"
navigation += "</li>"
navigation += "<li class='pipe' id='mainNav_pipe6'></li>"
navigation += "<li id='mainNav_item6'><a href='http://www.kroger.com/services' class='main'><img src='http://www.kroger.com/SiteCollectionImages/common/navigation/kroger/mainNav_Services.gif' id='ctl00_Img6' alt='image' title='Services' /></a>"
navigation += "<ul id='mainNav_item6-menu' class='hide'>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/recall_information.aspx'>Recall Information</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/finance/Pages/default.aspx'>1-2-3 REWARDS&reg; Visa&reg;</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/finance/debit/Pages/default.aspx'>Visa&reg; Prepaid Debit Card</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/specialty_grocery.aspx'>Specialty Grocery</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/school_programs.aspx'>School Programs</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/phone_services.aspx'>Phone Services</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/partners.aspx'>Partners</a></li>"
navigation += "<li><a href='http://www.communitygifts.com/kroger'>Request a Donation</a></li>"
navigation += "<li><a href='http://www.kroger.com/mykroger/Pages/community_rewards.aspx'>Community Rewards</a></li>"
navigation += "</ul>"
navigation += "</li>"
navigation += "<li class='pipe' id='mainNav_pipe7'></li>"
navigation += "<li id='mainNav_item7'><a href='http://www.kroger.com/pharmacy' class='main'><img src='http://www.kroger.com/SiteCollectionImages/common/navigation/kroger/mainNav_Pharmacy.gif' id='ctl00_Img7' alt='image' title='Pharmacy' /></a>"
navigation += "<ul id='mainNav_item7-menu' class='hide'>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/order_prescriptions.aspx'>Prescriptions</a></li>"
navigation += "<li><a href='http://www.kroger.com/generic/'>Generic Program</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/vaccinations.aspx'>Vaccinations</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/travel_vaccinations.aspx/'>Travel Vaccinations</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/drug_information.aspx'>Drug Information</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/medical_forms.aspx'>Medical Forms</a></li>"
navigation += "<li><a href='http://www.kpp-rx.com/'>Prescription Drug Plans</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/the_little_clinic.aspx'>The Little Clinic</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/medicare_plans.aspx'>Medicare Plans</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/workplace_flu.aspx'>Workplace Flu</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/medication_disposal.aspx'>How to Dispose of Unused Medicines</a></li>"
navigation += "</ul>"
navigation += "</li>"
navigation += "<li class='pipe' id='mainNav_pipe8'></li>"
navigation += "<li id='mainNav_item8'><a href='http://www.kroger.com/in_store/Pages/default.aspx' class='main'><img src='http://www.kroger.com/SiteCollectionImages/common/navigation/kroger/mainNav_In_Store.gif' id='ctl00_Img8' alt='image' title='In Store' /></a>"
navigation += "<ul id='mainNav_item8-menu' class='hide'>"
navigation += "<li><a href='http://www.kroger.com/in_store/Pages/coupon_landing.aspx'>Coupons</a></li>"
navigation += "<li><a href='http://www.kroger.com/in_store/Pages/savings.aspx'>Savings</a></li>"
navigation += "<li><a href='http://www.kroger.com/in_store/Pages/promotions.aspx'>Promotions</a></li>"
navigation += "<li><a href='http://www.kroger.com/in_store/fuel/Pages/default.aspx'>Save on Fuel</a></li>"
navigation += "<li><a href='http://www.kroger.com/in_store/corporate_brands/Pages/default.aspx'>Our Exclusive Brands</a></li>"
navigation += "<li><a href='http://www.startsampling.com/retail/kroger/'>Samples</a></li>"
navigation += "<li><a href='http://www.kroger.com/IN_STORE/NEW_PRODUCTS/Pages/default.aspx'>New Products</a></li>"
navigation += "<li><a href='http://services.kroger.com/mapquest/storesearchadvanced.aspx'>Weekly Ads</a></li>"
navigation += "</ul>"
navigation += "</li>"
navigation += "<li class='pipe' id='mainNav_pipe9'></li>"
navigation += "<li id='mainNav_item9'><a href='#' class='main'><img src='http://www.kroger.com/SiteCollectionImages/common/navigation/kroger/mainNav_SeeAll.gif' id='ctl00_Img12' alt='image' title='See All' /></a>"
navigation += "<div id='mainNav_item9-menu' class='hide'>"
navigation += "<div class='body'>"
navigation += "<div class='columnEntry'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/company_information/Pages/default.aspx' class='header'>Company Information</a></li>"
navigation += "<li><a href='http://www.thekrogerco.com/'>About The Kroger Co.</a></li>"
navigation += "<li><a href='http://www.thekrogerco.com/corpnews/corpnewsinfo.htm'>Company News</a></li>"
navigation += "<li><a href='http://www.thekrogerco.com/finance/financialinfo.htm'>Investor Relations</a></li>"
navigation += "<li><a href='http://www.thekrogerco.com/finance/financialinfo_reportsandstatements.htm'>SEC Filings</a></li>"
navigation += "<li><a href='http://www.kroger.com/company_information/community/Pages/default.aspx'>Community</a></li>"
navigation += "<li><a href='http://www.krogerrealestate.com/'>Kroger Real Estate</a></li>"
navigation += "<li><a href='http://www.kroger.com/company_information/jobs/Pages/default.aspx'>Jobs</a></li>"
navigation += "<li><a href='https://ess.kroger.com/'>Associates</a></li>"
navigation += "<li><span>&nbsp;</span></li>"
navigation += "<li class='noBorder'><span>&nbsp;</span></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div class='columnEntry'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/fresh_foods' class='header'>Fresh Foods</a></li>"
navigation += "<li><a href='http://www.kroger.com/fresh_foods/deli_bakery/Pages/default.aspx'>Deli & Bakery</a></li>"
navigation += "<li><a href='http://www.kroger.com/fresh_foods/fruits_veggies/Pages/default.aspx'>Fruits & Veggies</a></li>"
navigation += "<li><a href='http://www.kroger.com/fresh_foods/meat_seafood/Pages/default.aspx'>Meat & Seafood</a></li>"
navigation += "<li><span>&nbsp;</span></li>"
navigation += "<li class='noBorder'><span>&nbsp;</span></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div class='columnEntry'>"
navigation += "<ul>"
navigation += "<li><a  href='http://www.kroger.com/great_meals' class='header'>Great Meals</a></li>"
navigation += "<li><a  href='http://www.kroger.com/great_meals/recipes/Pages/default.aspx'>Recipes</a></li>"
navigation += "<li><a  href='http://www.kroger.com/great_meals/party_planning/Pages/default.aspx'>Party Planning</a></li>" 
navigation += "<li><a  href='http://www.kroger.com/great_meals/safe_food_preparation/Pages/default.aspx'>Safe Food Preparation</a></li>"
navigation += "<li><a  href='http://www.kroger.com/great_meals/party_trays/Pages/default.aspx'>Party Trays</a></li>"
navigation += "<li><a  href='http://www.krogerbeerevents.com'>Beer</a></li>"
navigation += "<li><a  href='http://www.krogerwineevents.com'>Wine</a></li>"
navigation += "<li><a  href='http://krogerspiritevents.com/'>Spirits</a></li>"
navigation += "<li><span>&nbsp;</span></li>"
navigation += "<li class='noBorder'><span>&nbsp;</span></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div class='columnEntry'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/healthy_living' class='header'>Healthy Living</a></li>"
navigation += "<li><a href='http://kroger.staywellsolutionsonline.com/'>Health Guide</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/the_little_clinic.aspx'>The Little Clinic</a></li>"
navigation += "<li><a href='http://www.kroger.com/healthy_living/family/Pages/default.aspx'>Home & Family</a></li>"
navigation += "<li><a href='http://www.kroger.com/healthy_living/fitness_nutrition/Pages/default.aspx'>Fitness & Nutrition</a></li>"
navigation += "<li><a href='http://www.kroger.com/healthy_living/green_living/Pages/default.aspx'>Green Living</a></li>"
navigation += "<li><a href='http://www.kroger.com/healthy_living/gluten_free/Pages/default.aspx'>Gluten Free</a></li>"
navigation += "<li><span>&nbsp;</span></li>"
navigation += "<li class='noBorder'><span>&nbsp;</span></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div class='columnEntryLast'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/help/Pages/default.aspx' class='header'>Help</a></li>"
navigation += "<li><a href='http://www.kroger.com/help/Pages/contact_us.aspx'>Contact Us</a></li>"
navigation += "<li><a href='https://customer.kroger.com/comments/comments.aspx'>Customer Comments</a></li>"
navigation += "<li><a href='http://recipes.kroger.com/faqs/browse.aspx'>FAQs</a></li>"
navigation += "<li><a href='http://www.kroger.com/help/Pages/site_map.aspx'>Site Map</a></li>"
navigation += "<li><span>&nbsp;</span></li>"
navigation += "<li class='noBorder'><span>&nbsp;</span></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div class='clear'>"
navigation += "</div>"
navigation += "<div class='columnEntry'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/pharmacy' class='header'>Pharmacy</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/order_prescriptions.aspx'>Prescriptions</a></li>"
navigation += "<li><a href='http://www.kroger.com/generic/'>Generic Program</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/vaccinations.aspx'>Vaccinations</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/travel_vaccinations.aspx/'>Travel Vaccinations</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/drug_information.aspx'>Drug Information</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/medical_forms.aspx'>Medical Forms</a></li>"
navigation += "<li><a href='http://www.kpp-rx.com/'>Prescription Drug Plans</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/the_little_clinic.aspx'>The Little Clinic</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/medicare_plans.aspx'>Medicare Plans</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/workplace_flu.aspx'>Workplace Flu</a></li>"
navigation += "<li><a href='http://www.kroger.com/pharmacy/Pages/medication_disposal.aspx'>How to Dispose of Unused Medicines</a></li>"
navigation += "<li class='noBorder'><span>&nbsp;</span></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div class='columnEntry'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/services' class='header'>Services</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/recall_information.aspx'>Recall Information</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/finance/Pages/default.aspx'>1-2-3 REWARDS&reg; Visa&reg;</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/finance/debit/Pages/default.aspx'>Visa&reg; Prepaid Debit Card</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/specialty_grocery.aspx'>Specialty Grocery</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/school_programs.aspx'>School Programs</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/phone_services.aspx'>Phone Services</a></li>"
navigation += "<li><a href='http://www.kroger.com/services/Pages/partners.aspx'>Partners</a></li>"
navigation += "<li><a href='http://www.communitygifts.com/kroger'>Request a Donation</a></li>"
navigation += "<li><a href='http://www.kroger.com/mykroger/Pages/community_rewards.aspx'>Community Rewards</a></li>"
navigation += "<li class='noBorder'><span>&nbsp;</span></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div class='columnEntry'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/gift_center' class='header'>Gift Center</a></li>"
navigation += "<li><a href='http://www.kroger.com/gift_center/gc/Pages/default.aspx'>Buy Gift Cards</a></li>"
navigation += "<li><a href='http://ftdfloristsonline.com/kroger'>Flowers</a></li>"
navigation += "<li><a href='http://www.kroger.com/gift_center/Pages/gourmet_gifts.aspx'>Gourmet Gifts</a></li>"
navigation += "<li><a href='http://www.kroger.com/gift_center/Pages/jewelry.aspx'>Fred Meyer Jewelers</a></li>"
navigation += "<li class='noBorder'><span>&nbsp;</span></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div class='columnEntry'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/stores/Pages/default.aspx' class='header'>Stores</a></li>"
navigation += "<li><a href='http://services.kroger.com/StoreLocator/StoreLocatorAdvanced.aspx'>Store Locator</a></li>"
navigation += "<li><a href='http://services.kroger.com/StoreLocator/StoreLocatorWeeklyAdSearch.aspx '>Weekly Ads</a></li>"
navigation += "<li><a href='http://www.kroger.com/stores/our_exclusive_brands/Pages/our_exclusive_brands.aspx'>Our Exclusive Brands</a></li>"
navigation += "<li class='noBorder'><span>&nbsp;</span></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "<div class='columnEntryLast'>"
navigation += "<ul>"
navigation += "<li><a href='http://www.kroger.com/in_store/Pages/default.aspx' class='header'>In Store</a></li>"
navigation += "<li><a href='http://www.kroger.com/in_store/Pages/coupon_landing.aspx'>Coupons</a></li>"
navigation += "<li><a href='http://www.kroger.com/in_store/Pages/savings.aspx'>Savings</a></li>"
navigation += "<li><a href='http://www.kroger.com/in_store/Pages/promotions.aspx'>Promotions</a></li>"
navigation += "<li><a href='http://www.kroger.com/in_store/corporate_brands/Pages/default.aspx'>Our Exclusive Brands</a></li>"
navigation += "<li><a href='http://www.startsampling.com/retail/kroger/'>Samples</a></li>"
navigation += "<li><a href='http://www.kroger.com/IN_STORE/FUEL/Pages/default.aspx'>Save on Fuel</a></li>"
navigation += "<li><a href='http://www.kroger.com/IN_STORE/NEW_PRODUCTS/Pages/default.aspx'>New Products</a></li>"
navigation += "<li><a href='http://services.kroger.com/StoreLocator/StoreLocatorWeeklyAdSearch.aspx'>Weekly Ads</a></li>"
navigation += "<li class='noBorder'><span>&nbsp;</span></li>"
navigation += "</ul>"
navigation += "</div>"
navigation += "</div>"
navigation += "</div>"
navigation += "</li>"
navigation += "</li>"
navigation += "<li class='pipe' id='mainNav_pipe10'></li>"
document.write(navigation);